### ISSUE TITLE
Can you provide your settings and changes in running Know-Evovle code?

### ISSUE THREAD

**Issue by SeanLiaoy** [INK-USC/RE-Net#26]
Hi authors,

I am trying to reproduce the results of the Know-Evolve model in your paper. 
Now I can successfully run two example shells script in Know-Evolve on the original ICEWS dataset . However, when I changed it to datasets you provided, the program was able to perform the training normally but suddenly quit during the test. 

I also found that ICEWS14 dataset was came from Know-Evolve, and the first 2776 lines data in "train.txt" were deleted.
I ran Know-Evolve on all datasets including ICWES14 and encountered the same problem, the error information was described in https://github.com/rstriv/Know-Evolve/issues/11#issue-588912511

Can you provide your modified version of Know-Evovle code, or tell me the major changes to run it?
Thanks a lot!

**Comment by woojeongjin** [comment]
Hi, thanks for your interest.
1. What was the dataset?
2. That is because the first 2776 lines are for Know-evolve code. If you look into their data, they are self-loops to avoid error in the know-evolve. These are not necessary for my code.
3. In Know-Evolve/code/know_evolve/src/lib/sparse_onedim_rank_criterion_layer.cpp,
line 59-63 should be modified. This is the one causing the wrong behavior.
